name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Adjust as needed

      - name: Install dependencies
        run: yarn install

      - name: Build the app
        run: yarn build

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v2.2.2
        with:
          heroku_app_name: your-app-name
          heroku_email: your-email@example.com
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
